# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2016-12-12 01:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scheduler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='WeekHour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.PositiveSmallIntegerField(verbose_name='Hour in week (0 - 7*24')),
            ],
        ),
        migrations.AddField(
            model_name='scheduler',
            name='weekhours',
            field=models.ManyToManyField(related_name='schedulers', to='app.WeekHour'),
        ),
    ]
