# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2016-12-13 01:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20161211_1926'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='name of the book')),
                ('author_name', models.CharField(max_length=20, verbose_name='the name of the author')),
            ],
        ),
    ]
