# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2016-12-19 15:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20161212_1949'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveShowTimings',
            fields=[
                ('activeshowid', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='MovieActiveDays',
            fields=[
                ('date', models.DateField()),
                ('activedayid', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='MovieDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TheaterBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TheaterShowTimings',
            fields=[
                ('showname', models.CharField(max_length=100)),
                ('showtime', models.TimeField()),
                ('theatershowtimingsid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('movieActiveDays', models.ManyToManyField(through='app.ActiveShowTimings', to='app.MovieActiveDays')),
            ],
        ),
        migrations.AddField(
            model_name='movieactivedays',
            name='moviedetails',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.MovieDetails'),
        ),
        migrations.AddField(
            model_name='movieactivedays',
            name='theaterbase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.TheaterBase'),
        ),
        migrations.AddField(
            model_name='activeshowtimings',
            name='MovieActiveDays',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.MovieActiveDays'),
        ),
        migrations.AddField(
            model_name='activeshowtimings',
            name='TheaterShowTimings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.TheaterShowTimings'),
        ),
    ]
