# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2016-12-26 01:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20161219_0908'),
    ]

    operations = [
        migrations.CreateModel(
            name='Background',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bk_color', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='FormOne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('background', models.ManyToManyField(blank=True, to='app.Background')),
            ],
        ),
    ]
