# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2016-12-26 01:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_background_formone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formone',
            name='background',
        ),
        migrations.AddField(
            model_name='formone',
            name='background',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='app.Background'),
            preserve_default=False,
        ),
    ]
