# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-04 01:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_background_createat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('new_description', models.TextField(default=models.TextField())),
            ],
        ),
    ]
