# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 02:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20170220_0317'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_nm', models.CharField(blank=True, db_column='customer_nm', max_length=255, null=True)),
            ],
            options={
                'db_table': '"stage"."mytable"',
                'managed': False,
            },
        ),
    ]
