# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-18 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_mymodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, help_text='Creation date')),
                ('modified_date', models.DateTimeField(auto_now=True, help_text='Last modification date')),
                ('image_file', models.ImageField(null=True, upload_to='')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
            },
        ),
        migrations.AlterModelOptions(
            name='mymodel',
            options={'managed': True},
        ),
    ]
